
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/lib/python3.10/dist-packages/cmake/data/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:10 (project)"
    message: |
      The system is: Linux - 6.2.0-26-generic - x86_64
...
